openapi: 3.0.0
info:
  version: 1.4.0
  description: Create credit simulation
  title: Credit Simulator API
tags:
  - name: Simulations
    description: CRUD operations for simulator
paths:
  /api/v1/simulations/:
    get:
      tags:
        - Simulations
      summary: Return all recorded simulations
      operationId: getSimulationUsingGET
      parameters:
        - name: name
          in: query
          description: Search a simulation by a person name
          required: false
          allowEmptyValue: true
          schema:
            type: string
      responses:
        "200":
          description: Simulations found
          content:
            "application/json":
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Simulation"
        "404":
          description: Name not found
    post:
      tags:
        - Simulations
      summary: Record a new simulation
      operationId: newSimulationUsingPOST
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Simulation"
        description: Simulation object
        required: true
      responses:
        "201":
          description: Simulation created successfully
          headers:
            Location:
              description: URI to query the created simulation
              schema:
                type: string
        "403":
          description: CPF has a restriction
          content:
            "application/json":
              schema:
                $ref: "#/components/schemas/Message"
        "409":
          description: CPF already exists
        "422":
          description: Missing information
          content:
            "application/json":
              schema:
                $ref: "#/components/schemas/Validation"
  "/api/v1/simulations/{cpf}":
    get:
      tags:
        - Simulations
      summary: Return a simulation for a given CPF
      operationId: oneUsingGET_1
      parameters:
        - name: cpf
          in: path
          description: CPF to query an existing simulation
          required: true
          schema:
            type: string
      responses:
        "200":
          description: Simulations found
          content:
            "application/json":
              schema:
                $ref: "#/components/schemas/Simulation"
        "404":
          description: Simulations not found
    put:
      tags:
        - Simulations
      summary: Update a simulation by a given CPF
      operationId: updateSimulationUsingPUT
      parameters:
        - name: cpf
          in: path
          description: CPF to query an existing simulation
          required: true
          schema:
            type: string
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Simulation"
        description: Simulation object with data to update
        required: true
      responses:
        "200":
          description: Simulation updated successfully
          content:
            "application/json":
              schema:
                $ref: "#/components/schemas/Simulation"
        "404":
          description: Simulation not found
        "409":
          description: CPF already exists
    delete:
      tags:
        - Simulations
      summary: Delete a simulation by a given CPF
      operationId: deleteUsingDELETE
      parameters:
        - name: cpf
          in: path
          description: CPF to query an existing simulation
          required: true
          schema:
            type: string
      responses:
        "204":
          description: Simulation deleted successfully
        "404":
          description: Simulation not found
servers:
  - url: //localhost:8089/
components:
  schemas:
    Message:
      type: object
      required:
        - message
      properties:
        message:
          type: string
          example: CPF 999999999 has a restriction
      title: Message
    Simulation:
      type: object
      properties:
        cpf:
          type: string
          example: 9709323014
        email:
          type: string
          example: john.doe@gmail.com
          pattern: .+@.+\.[a-z]+
        name:
          type: string
          example: John Doe
        installments:
          type: integer
          format: int32
          example: 3
          minimum: 2
          maximum: 48
          exclusiveMinimum: false
          exclusiveMaximum: false
        insurance:
          type: boolean
          example: true
        amount:
          type: number
          example: 1200
          minimum: 1000
          maximum: 40000
          exclusiveMinimum: false
          exclusiveMaximum: false
      title: Simulation
    Validation:
      type: object
      properties:
        errors:
          type: object
          additionalProperties:
            type: string
      title: Validation